chore(scripts/test): bubble up exit codes from child processes

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,5 +1,19 @@
 #!/bin/bash
 
+safeRunCommand() {
+  typeset cmnd="$*"
+  typeset ret_code
+
+  echo cmnd=$cmnd
+  eval $cmnd
+
+  ret_code=$?
+  if [ $ret_code != 0 ]; then
+    printf "Error : [%d] when executing command: '$cmnd'" $ret_code
+    exit $ret_code
+  fi
+}
+
 # run local truffle node
 ganache-cli &
 sleep 5
@@ -15,15 +29,17 @@ cp -a test/fixtures/identities/. ~/.ara/identities/
 cd node_modules/ara-contracts
 truffle migrate --network local
 
-DEBUG=ara* act deploy standard 8a98c8305035dcbb1e8fa0826965200269e232e45ac572d26a45db9581986e67 -f -p pass \
-1 ./contracts/AFS.sol ./contracts/Library.sol ./contracts/Registry.sol ./contracts/Proxy.sol ./contracts/AraToken.sol &
+command="DEBUG=ara* act deploy standard 8a98c8305035dcbb1e8fa0826965200269e232e45ac572d26a45db9581986e67 -f -p pass \
+1 ./contracts/AFS.sol ./contracts/Library.sol ./contracts/Registry.sol ./contracts/Proxy.sol ./contracts/AraToken.sol &"
+safeRunCommand "$command"
 
 # deploy process doesn't close on its own, must sleep
 sleep 20
 
 cd ../..
 
-ava test --verbose
+command="ava test --verbose"
+safeRunCommand "$command"
 
 # cleanup
 pkill -f ganache
